using System;

namespace Nalarium.ExceptionHandling.Retry
{
    public delegate void ExceptionCatchBlock(Exception ex);
}